// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cop_balances.proto

// Protobuf Java Version: 3.25.1
package com.example.demo.proto;

public interface AccountIdentifierOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.proto.AccountIdentifier)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accountid = 1;</code>
   * @return The accountid.
   */
  String getAccountid();
  /**
   * <code>string accountid = 1;</code>
   * @return The bytes for accountid.
   */
  com.google.protobuf.ByteString
      getAccountidBytes();
}
