// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccp_balances.proto

// Protobuf Java Version: 3.25.1
package com.example.demo.proto;

/**
 * Protobuf type {@code com.example.proto.CcpBalances}
 */
public final class CcpBalances extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.proto.CcpBalances)
    CcpBalancesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CcpBalances.newBuilder() to construct.
  private CcpBalances(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CcpBalances() {
    exchangeName_ = "";
    status_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CcpBalances();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CcpBalancesOuterClass.internal_static_com_example_proto_CcpBalances_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CcpBalancesOuterClass.internal_static_com_example_proto_CcpBalances_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CcpBalances.class, Builder.class);
  }

  private int bitField0_;
  public static final int ACCOUNTIDENTIFIER_FIELD_NUMBER = 1;
  private AccountIdentifier accountIdentifier_;
  /**
   * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
   * @return Whether the accountIdentifier field is set.
   */
  @Override
  public boolean hasAccountIdentifier() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
   * @return The accountIdentifier.
   */
  @Override
  public AccountIdentifier getAccountIdentifier() {
    return accountIdentifier_ == null ? AccountIdentifier.getDefaultInstance() : accountIdentifier_;
  }
  /**
   * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
   */
  @Override
  public AccountIdentifierOrBuilder getAccountIdentifierOrBuilder() {
    return accountIdentifier_ == null ? AccountIdentifier.getDefaultInstance() : accountIdentifier_;
  }

  public static final int BUSINESSDATE_FIELD_NUMBER = 2;
  private int businessDate_ = 0;
  /**
   * <code>int32 businessDate = 2;</code>
   * @return The businessDate.
   */
  @Override
  public int getBusinessDate() {
    return businessDate_;
  }

  public static final int EXCHANGENAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object exchangeName_ = "";
  /**
   * <code>string exchangeName = 3;</code>
   * @return The exchangeName.
   */
  @Override
  public String getExchangeName() {
    Object ref = exchangeName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      exchangeName_ = s;
      return s;
    }
  }
  /**
   * <code>string exchangeName = 3;</code>
   * @return The bytes for exchangeName.
   */
  @Override
  public com.google.protobuf.ByteString
      getExchangeNameBytes() {
    Object ref = exchangeName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      exchangeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRADEDETAILS_FIELD_NUMBER = 4;
  private TradeDetails tradeDetails_;
  /**
   * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
   * @return Whether the tradeDetails field is set.
   */
  @Override
  public boolean hasTradeDetails() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
   * @return The tradeDetails.
   */
  @Override
  public TradeDetails getTradeDetails() {
    return tradeDetails_ == null ? TradeDetails.getDefaultInstance() : tradeDetails_;
  }
  /**
   * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
   */
  @Override
  public TradeDetailsOrBuilder getTradeDetailsOrBuilder() {
    return tradeDetails_ == null ? TradeDetails.getDefaultInstance() : tradeDetails_;
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private int status_ = 0;
  /**
   * <code>.com.example.proto.Status status = 5;</code>
   * @return The enum numeric value on the wire for status.
   */
  @Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.com.example.proto.Status status = 5;</code>
   * @return The status.
   */
  @Override public Status getStatus() {
    Status result = Status.forNumber(status_);
    return result == null ? Status.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getAccountIdentifier());
    }
    if (businessDate_ != 0) {
      output.writeInt32(2, businessDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exchangeName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, exchangeName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getTradeDetails());
    }
    if (status_ != Status.UNKNOWN.getNumber()) {
      output.writeEnum(5, status_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAccountIdentifier());
    }
    if (businessDate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, businessDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exchangeName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, exchangeName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTradeDetails());
    }
    if (status_ != Status.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, status_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CcpBalances)) {
      return super.equals(obj);
    }
    CcpBalances other = (CcpBalances) obj;

    if (hasAccountIdentifier() != other.hasAccountIdentifier()) return false;
    if (hasAccountIdentifier()) {
      if (!getAccountIdentifier()
          .equals(other.getAccountIdentifier())) return false;
    }
    if (getBusinessDate()
        != other.getBusinessDate()) return false;
    if (!getExchangeName()
        .equals(other.getExchangeName())) return false;
    if (hasTradeDetails() != other.hasTradeDetails()) return false;
    if (hasTradeDetails()) {
      if (!getTradeDetails()
          .equals(other.getTradeDetails())) return false;
    }
    if (status_ != other.status_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAccountIdentifier()) {
      hash = (37 * hash) + ACCOUNTIDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getAccountIdentifier().hashCode();
    }
    hash = (37 * hash) + BUSINESSDATE_FIELD_NUMBER;
    hash = (53 * hash) + getBusinessDate();
    hash = (37 * hash) + EXCHANGENAME_FIELD_NUMBER;
    hash = (53 * hash) + getExchangeName().hashCode();
    if (hasTradeDetails()) {
      hash = (37 * hash) + TRADEDETAILS_FIELD_NUMBER;
      hash = (53 * hash) + getTradeDetails().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CcpBalances parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CcpBalances parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CcpBalances parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CcpBalances parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CcpBalances parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CcpBalances parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CcpBalances parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CcpBalances parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static CcpBalances parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static CcpBalances parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CcpBalances parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CcpBalances parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CcpBalances prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.proto.CcpBalances}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.proto.CcpBalances)
      CcpBalancesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CcpBalancesOuterClass.internal_static_com_example_proto_CcpBalances_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CcpBalancesOuterClass.internal_static_com_example_proto_CcpBalances_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CcpBalances.class, Builder.class);
    }

    // Construct using com.example.demo.proto.CcpBalances.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAccountIdentifierFieldBuilder();
        getTradeDetailsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      accountIdentifier_ = null;
      if (accountIdentifierBuilder_ != null) {
        accountIdentifierBuilder_.dispose();
        accountIdentifierBuilder_ = null;
      }
      businessDate_ = 0;
      exchangeName_ = "";
      tradeDetails_ = null;
      if (tradeDetailsBuilder_ != null) {
        tradeDetailsBuilder_.dispose();
        tradeDetailsBuilder_ = null;
      }
      status_ = 0;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CcpBalancesOuterClass.internal_static_com_example_proto_CcpBalances_descriptor;
    }

    @Override
    public CcpBalances getDefaultInstanceForType() {
      return CcpBalances.getDefaultInstance();
    }

    @Override
    public CcpBalances build() {
      CcpBalances result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CcpBalances buildPartial() {
      CcpBalances result = new CcpBalances(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(CcpBalances result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.accountIdentifier_ = accountIdentifierBuilder_ == null
            ? accountIdentifier_
            : accountIdentifierBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.businessDate_ = businessDate_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.exchangeName_ = exchangeName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tradeDetails_ = tradeDetailsBuilder_ == null
            ? tradeDetails_
            : tradeDetailsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.status_ = status_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CcpBalances) {
        return mergeFrom((CcpBalances)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CcpBalances other) {
      if (other == CcpBalances.getDefaultInstance()) return this;
      if (other.hasAccountIdentifier()) {
        mergeAccountIdentifier(other.getAccountIdentifier());
      }
      if (other.getBusinessDate() != 0) {
        setBusinessDate(other.getBusinessDate());
      }
      if (!other.getExchangeName().isEmpty()) {
        exchangeName_ = other.exchangeName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasTradeDetails()) {
        mergeTradeDetails(other.getTradeDetails());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getAccountIdentifierFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              businessDate_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              exchangeName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getTradeDetailsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private AccountIdentifier accountIdentifier_;
    private com.google.protobuf.SingleFieldBuilderV3<
        AccountIdentifier, AccountIdentifier.Builder, AccountIdentifierOrBuilder> accountIdentifierBuilder_;
    /**
     * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
     * @return Whether the accountIdentifier field is set.
     */
    public boolean hasAccountIdentifier() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
     * @return The accountIdentifier.
     */
    public AccountIdentifier getAccountIdentifier() {
      if (accountIdentifierBuilder_ == null) {
        return accountIdentifier_ == null ? AccountIdentifier.getDefaultInstance() : accountIdentifier_;
      } else {
        return accountIdentifierBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
     */
    public Builder setAccountIdentifier(AccountIdentifier value) {
      if (accountIdentifierBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        accountIdentifier_ = value;
      } else {
        accountIdentifierBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
     */
    public Builder setAccountIdentifier(
        AccountIdentifier.Builder builderForValue) {
      if (accountIdentifierBuilder_ == null) {
        accountIdentifier_ = builderForValue.build();
      } else {
        accountIdentifierBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
     */
    public Builder mergeAccountIdentifier(AccountIdentifier value) {
      if (accountIdentifierBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          accountIdentifier_ != null &&
          accountIdentifier_ != AccountIdentifier.getDefaultInstance()) {
          getAccountIdentifierBuilder().mergeFrom(value);
        } else {
          accountIdentifier_ = value;
        }
      } else {
        accountIdentifierBuilder_.mergeFrom(value);
      }
      if (accountIdentifier_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
     */
    public Builder clearAccountIdentifier() {
      bitField0_ = (bitField0_ & ~0x00000001);
      accountIdentifier_ = null;
      if (accountIdentifierBuilder_ != null) {
        accountIdentifierBuilder_.dispose();
        accountIdentifierBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
     */
    public AccountIdentifier.Builder getAccountIdentifierBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getAccountIdentifierFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
     */
    public AccountIdentifierOrBuilder getAccountIdentifierOrBuilder() {
      if (accountIdentifierBuilder_ != null) {
        return accountIdentifierBuilder_.getMessageOrBuilder();
      } else {
        return accountIdentifier_ == null ?
            AccountIdentifier.getDefaultInstance() : accountIdentifier_;
      }
    }
    /**
     * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        AccountIdentifier, AccountIdentifier.Builder, AccountIdentifierOrBuilder>
        getAccountIdentifierFieldBuilder() {
      if (accountIdentifierBuilder_ == null) {
        accountIdentifierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            AccountIdentifier, AccountIdentifier.Builder, AccountIdentifierOrBuilder>(
                getAccountIdentifier(),
                getParentForChildren(),
                isClean());
        accountIdentifier_ = null;
      }
      return accountIdentifierBuilder_;
    }

    private int businessDate_ ;
    /**
     * <code>int32 businessDate = 2;</code>
     * @return The businessDate.
     */
    @Override
    public int getBusinessDate() {
      return businessDate_;
    }
    /**
     * <code>int32 businessDate = 2;</code>
     * @param value The businessDate to set.
     * @return This builder for chaining.
     */
    public Builder setBusinessDate(int value) {

      businessDate_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 businessDate = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBusinessDate() {
      bitField0_ = (bitField0_ & ~0x00000002);
      businessDate_ = 0;
      onChanged();
      return this;
    }

    private Object exchangeName_ = "";
    /**
     * <code>string exchangeName = 3;</code>
     * @return The exchangeName.
     */
    public String getExchangeName() {
      Object ref = exchangeName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        exchangeName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string exchangeName = 3;</code>
     * @return The bytes for exchangeName.
     */
    public com.google.protobuf.ByteString
        getExchangeNameBytes() {
      Object ref = exchangeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        exchangeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string exchangeName = 3;</code>
     * @param value The exchangeName to set.
     * @return This builder for chaining.
     */
    public Builder setExchangeName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      exchangeName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string exchangeName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExchangeName() {
      exchangeName_ = getDefaultInstance().getExchangeName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string exchangeName = 3;</code>
     * @param value The bytes for exchangeName to set.
     * @return This builder for chaining.
     */
    public Builder setExchangeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      exchangeName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private TradeDetails tradeDetails_;
    private com.google.protobuf.SingleFieldBuilderV3<
        TradeDetails, TradeDetails.Builder, TradeDetailsOrBuilder> tradeDetailsBuilder_;
    /**
     * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
     * @return Whether the tradeDetails field is set.
     */
    public boolean hasTradeDetails() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
     * @return The tradeDetails.
     */
    public TradeDetails getTradeDetails() {
      if (tradeDetailsBuilder_ == null) {
        return tradeDetails_ == null ? TradeDetails.getDefaultInstance() : tradeDetails_;
      } else {
        return tradeDetailsBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
     */
    public Builder setTradeDetails(TradeDetails value) {
      if (tradeDetailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tradeDetails_ = value;
      } else {
        tradeDetailsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
     */
    public Builder setTradeDetails(
        TradeDetails.Builder builderForValue) {
      if (tradeDetailsBuilder_ == null) {
        tradeDetails_ = builderForValue.build();
      } else {
        tradeDetailsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
     */
    public Builder mergeTradeDetails(TradeDetails value) {
      if (tradeDetailsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          tradeDetails_ != null &&
          tradeDetails_ != TradeDetails.getDefaultInstance()) {
          getTradeDetailsBuilder().mergeFrom(value);
        } else {
          tradeDetails_ = value;
        }
      } else {
        tradeDetailsBuilder_.mergeFrom(value);
      }
      if (tradeDetails_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
     */
    public Builder clearTradeDetails() {
      bitField0_ = (bitField0_ & ~0x00000008);
      tradeDetails_ = null;
      if (tradeDetailsBuilder_ != null) {
        tradeDetailsBuilder_.dispose();
        tradeDetailsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
     */
    public TradeDetails.Builder getTradeDetailsBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getTradeDetailsFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
     */
    public TradeDetailsOrBuilder getTradeDetailsOrBuilder() {
      if (tradeDetailsBuilder_ != null) {
        return tradeDetailsBuilder_.getMessageOrBuilder();
      } else {
        return tradeDetails_ == null ?
            TradeDetails.getDefaultInstance() : tradeDetails_;
      }
    }
    /**
     * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        TradeDetails, TradeDetails.Builder, TradeDetailsOrBuilder>
        getTradeDetailsFieldBuilder() {
      if (tradeDetailsBuilder_ == null) {
        tradeDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            TradeDetails, TradeDetails.Builder, TradeDetailsOrBuilder>(
                getTradeDetails(),
                getParentForChildren(),
                isClean());
        tradeDetails_ = null;
      }
      return tradeDetailsBuilder_;
    }

    private int status_ = 0;
    /**
     * <code>.com.example.proto.Status status = 5;</code>
     * @return The enum numeric value on the wire for status.
     */
    @Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.example.proto.Status status = 5;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.proto.Status status = 5;</code>
     * @return The status.
     */
    @Override
    public Status getStatus() {
      Status result = Status.forNumber(status_);
      return result == null ? Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.example.proto.Status status = 5;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.proto.Status status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000010);
      status_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.proto.CcpBalances)
  }

  // @@protoc_insertion_point(class_scope:com.example.proto.CcpBalances)
  private static final CcpBalances DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CcpBalances();
  }

  public static CcpBalances getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CcpBalances>
      PARSER = new com.google.protobuf.AbstractParser<CcpBalances>() {
    @Override
    public CcpBalances parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CcpBalances> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CcpBalances> getParserForType() {
    return PARSER;
  }

  @Override
  public CcpBalances getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

