// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cop_balances.proto

// Protobuf Java Version: 3.25.1
package com.example.demo.proto;

public interface CopBalancesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.proto.CopBalances)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
   * @return Whether the accountIdentifier field is set.
   */
  boolean hasAccountIdentifier();
  /**
   * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
   * @return The accountIdentifier.
   */
  AccountIdentifier getAccountIdentifier();
  /**
   * <code>.com.example.proto.AccountIdentifier accountIdentifier = 1;</code>
   */
  AccountIdentifierOrBuilder getAccountIdentifierOrBuilder();

  /**
   * <code>int32 businessDate = 2;</code>
   * @return The businessDate.
   */
  int getBusinessDate();

  /**
   * <code>string exchangeName = 3;</code>
   * @return The exchangeName.
   */
  String getExchangeName();
  /**
   * <code>string exchangeName = 3;</code>
   * @return The bytes for exchangeName.
   */
  com.google.protobuf.ByteString
      getExchangeNameBytes();

  /**
   * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
   * @return Whether the tradeDetails field is set.
   */
  boolean hasTradeDetails();
  /**
   * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
   * @return The tradeDetails.
   */
  TradeDetails getTradeDetails();
  /**
   * <code>.com.example.proto.TradeDetails tradeDetails = 4;</code>
   */
  TradeDetailsOrBuilder getTradeDetailsOrBuilder();

  /**
   * <code>.com.example.proto.Status status = 5;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.com.example.proto.Status status = 5;</code>
   * @return The status.
   */
  Status getStatus();
}
