// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccp_balances.proto

// Protobuf Java Version: 3.25.1
package com.example.demo.proto;

public interface NestedTradeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.proto.NestedTradeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string securityCode = 1;</code>
   * @return The securityCode.
   */
  String getSecurityCode();
  /**
   * <code>string securityCode = 1;</code>
   * @return The bytes for securityCode.
   */
  com.google.protobuf.ByteString
      getSecurityCodeBytes();

  /**
   * <code>double quantity = 2;</code>
   * @return The quantity.
   */
  double getQuantity();
}
