// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccp_balances.proto

// Protobuf Java Version: 3.25.1
package com.example.demo.proto;

/**
 * Protobuf type {@code com.example.proto.NestedTradeInfo}
 */
public final class NestedTradeInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.proto.NestedTradeInfo)
    NestedTradeInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NestedTradeInfo.newBuilder() to construct.
  private NestedTradeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NestedTradeInfo() {
    securityCode_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new NestedTradeInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CcpBalancesOuterClass.internal_static_com_example_proto_NestedTradeInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CcpBalancesOuterClass.internal_static_com_example_proto_NestedTradeInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NestedTradeInfo.class, Builder.class);
  }

  public static final int SECURITYCODE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object securityCode_ = "";
  /**
   * <code>string securityCode = 1;</code>
   * @return The securityCode.
   */
  @Override
  public String getSecurityCode() {
    Object ref = securityCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      securityCode_ = s;
      return s;
    }
  }
  /**
   * <code>string securityCode = 1;</code>
   * @return The bytes for securityCode.
   */
  @Override
  public com.google.protobuf.ByteString
      getSecurityCodeBytes() {
    Object ref = securityCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      securityCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 2;
  private double quantity_ = 0D;
  /**
   * <code>double quantity = 2;</code>
   * @return The quantity.
   */
  @Override
  public double getQuantity() {
    return quantity_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(securityCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, securityCode_);
    }
    if (Double.doubleToRawLongBits(quantity_) != 0) {
      output.writeDouble(2, quantity_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(securityCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, securityCode_);
    }
    if (Double.doubleToRawLongBits(quantity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, quantity_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NestedTradeInfo)) {
      return super.equals(obj);
    }
    NestedTradeInfo other = (NestedTradeInfo) obj;

    if (!getSecurityCode()
        .equals(other.getSecurityCode())) return false;
    if (Double.doubleToLongBits(getQuantity())
        != Double.doubleToLongBits(
            other.getQuantity())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SECURITYCODE_FIELD_NUMBER;
    hash = (53 * hash) + getSecurityCode().hashCode();
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getQuantity()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NestedTradeInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NestedTradeInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NestedTradeInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NestedTradeInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NestedTradeInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NestedTradeInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NestedTradeInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NestedTradeInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static NestedTradeInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static NestedTradeInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NestedTradeInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NestedTradeInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NestedTradeInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.proto.NestedTradeInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.proto.NestedTradeInfo)
      NestedTradeInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CcpBalancesOuterClass.internal_static_com_example_proto_NestedTradeInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CcpBalancesOuterClass.internal_static_com_example_proto_NestedTradeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NestedTradeInfo.class, Builder.class);
    }

    // Construct using com.example.demo.proto.NestedTradeInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      securityCode_ = "";
      quantity_ = 0D;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CcpBalancesOuterClass.internal_static_com_example_proto_NestedTradeInfo_descriptor;
    }

    @Override
    public NestedTradeInfo getDefaultInstanceForType() {
      return NestedTradeInfo.getDefaultInstance();
    }

    @Override
    public NestedTradeInfo build() {
      NestedTradeInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public NestedTradeInfo buildPartial() {
      NestedTradeInfo result = new NestedTradeInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(NestedTradeInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.securityCode_ = securityCode_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.quantity_ = quantity_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NestedTradeInfo) {
        return mergeFrom((NestedTradeInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NestedTradeInfo other) {
      if (other == NestedTradeInfo.getDefaultInstance()) return this;
      if (!other.getSecurityCode().isEmpty()) {
        securityCode_ = other.securityCode_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getQuantity() != 0D) {
        setQuantity(other.getQuantity());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              securityCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              quantity_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object securityCode_ = "";
    /**
     * <code>string securityCode = 1;</code>
     * @return The securityCode.
     */
    public String getSecurityCode() {
      Object ref = securityCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        securityCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string securityCode = 1;</code>
     * @return The bytes for securityCode.
     */
    public com.google.protobuf.ByteString
        getSecurityCodeBytes() {
      Object ref = securityCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        securityCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string securityCode = 1;</code>
     * @param value The securityCode to set.
     * @return This builder for chaining.
     */
    public Builder setSecurityCode(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      securityCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string securityCode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecurityCode() {
      securityCode_ = getDefaultInstance().getSecurityCode();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string securityCode = 1;</code>
     * @param value The bytes for securityCode to set.
     * @return This builder for chaining.
     */
    public Builder setSecurityCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      securityCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double quantity_ ;
    /**
     * <code>double quantity = 2;</code>
     * @return The quantity.
     */
    @Override
    public double getQuantity() {
      return quantity_;
    }
    /**
     * <code>double quantity = 2;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(double value) {

      quantity_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double quantity = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000002);
      quantity_ = 0D;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.proto.NestedTradeInfo)
  }

  // @@protoc_insertion_point(class_scope:com.example.proto.NestedTradeInfo)
  private static final NestedTradeInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NestedTradeInfo();
  }

  public static NestedTradeInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NestedTradeInfo>
      PARSER = new com.google.protobuf.AbstractParser<NestedTradeInfo>() {
    @Override
    public NestedTradeInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NestedTradeInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NestedTradeInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public NestedTradeInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

