// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cop_balances.proto

// Protobuf Java Version: 3.25.1
package com.example.demo.proto;

/**
 * Protobuf type {@code com.example.proto.TradeDetails}
 */
public final class TradeDetails extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.proto.TradeDetails)
    TradeDetailsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TradeDetails.newBuilder() to construct.
  private TradeDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TradeDetails() {
    tradeId_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TradeDetails();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CopBalancesOuterClass.internal_static_com_example_proto_TradeDetails_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CopBalancesOuterClass.internal_static_com_example_proto_TradeDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TradeDetails.class, Builder.class);
  }

  private int bitField0_;
  public static final int TRADEID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object tradeId_ = "";
  /**
   * <code>string tradeId = 1;</code>
   * @return The tradeId.
   */
  @Override
  public String getTradeId() {
    Object ref = tradeId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tradeId_ = s;
      return s;
    }
  }
  /**
   * <code>string tradeId = 1;</code>
   * @return The bytes for tradeId.
   */
  @Override
  public com.google.protobuf.ByteString
      getTradeIdBytes() {
    Object ref = tradeId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tradeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NESTEDTRADEINFO_FIELD_NUMBER = 2;
  private NestedTradeInfo nestedTradeInfo_;
  /**
   * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
   * @return Whether the nestedTradeInfo field is set.
   */
  @Override
  public boolean hasNestedTradeInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
   * @return The nestedTradeInfo.
   */
  @Override
  public NestedTradeInfo getNestedTradeInfo() {
    return nestedTradeInfo_ == null ? NestedTradeInfo.getDefaultInstance() : nestedTradeInfo_;
  }
  /**
   * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
   */
  @Override
  public NestedTradeInfoOrBuilder getNestedTradeInfoOrBuilder() {
    return nestedTradeInfo_ == null ? NestedTradeInfo.getDefaultInstance() : nestedTradeInfo_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tradeId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tradeId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getNestedTradeInfo());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tradeId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tradeId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getNestedTradeInfo());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TradeDetails)) {
      return super.equals(obj);
    }
    TradeDetails other = (TradeDetails) obj;

    if (!getTradeId()
        .equals(other.getTradeId())) return false;
    if (hasNestedTradeInfo() != other.hasNestedTradeInfo()) return false;
    if (hasNestedTradeInfo()) {
      if (!getNestedTradeInfo()
          .equals(other.getNestedTradeInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRADEID_FIELD_NUMBER;
    hash = (53 * hash) + getTradeId().hashCode();
    if (hasNestedTradeInfo()) {
      hash = (37 * hash) + NESTEDTRADEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getNestedTradeInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TradeDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TradeDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TradeDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TradeDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TradeDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TradeDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TradeDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TradeDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static TradeDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static TradeDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TradeDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TradeDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TradeDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.proto.TradeDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.proto.TradeDetails)
      TradeDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CopBalancesOuterClass.internal_static_com_example_proto_TradeDetails_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CopBalancesOuterClass.internal_static_com_example_proto_TradeDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TradeDetails.class, Builder.class);
    }

    // Construct using com.example.demo.proto.TradeDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNestedTradeInfoFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tradeId_ = "";
      nestedTradeInfo_ = null;
      if (nestedTradeInfoBuilder_ != null) {
        nestedTradeInfoBuilder_.dispose();
        nestedTradeInfoBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CopBalancesOuterClass.internal_static_com_example_proto_TradeDetails_descriptor;
    }

    @Override
    public TradeDetails getDefaultInstanceForType() {
      return TradeDetails.getDefaultInstance();
    }

    @Override
    public TradeDetails build() {
      TradeDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TradeDetails buildPartial() {
      TradeDetails result = new TradeDetails(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(TradeDetails result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tradeId_ = tradeId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nestedTradeInfo_ = nestedTradeInfoBuilder_ == null
            ? nestedTradeInfo_
            : nestedTradeInfoBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TradeDetails) {
        return mergeFrom((TradeDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TradeDetails other) {
      if (other == TradeDetails.getDefaultInstance()) return this;
      if (!other.getTradeId().isEmpty()) {
        tradeId_ = other.tradeId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasNestedTradeInfo()) {
        mergeNestedTradeInfo(other.getNestedTradeInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tradeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getNestedTradeInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object tradeId_ = "";
    /**
     * <code>string tradeId = 1;</code>
     * @return The tradeId.
     */
    public String getTradeId() {
      Object ref = tradeId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tradeId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string tradeId = 1;</code>
     * @return The bytes for tradeId.
     */
    public com.google.protobuf.ByteString
        getTradeIdBytes() {
      Object ref = tradeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tradeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tradeId = 1;</code>
     * @param value The tradeId to set.
     * @return This builder for chaining.
     */
    public Builder setTradeId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      tradeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string tradeId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTradeId() {
      tradeId_ = getDefaultInstance().getTradeId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string tradeId = 1;</code>
     * @param value The bytes for tradeId to set.
     * @return This builder for chaining.
     */
    public Builder setTradeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tradeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private NestedTradeInfo nestedTradeInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        NestedTradeInfo, NestedTradeInfo.Builder, NestedTradeInfoOrBuilder> nestedTradeInfoBuilder_;
    /**
     * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
     * @return Whether the nestedTradeInfo field is set.
     */
    public boolean hasNestedTradeInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
     * @return The nestedTradeInfo.
     */
    public NestedTradeInfo getNestedTradeInfo() {
      if (nestedTradeInfoBuilder_ == null) {
        return nestedTradeInfo_ == null ? NestedTradeInfo.getDefaultInstance() : nestedTradeInfo_;
      } else {
        return nestedTradeInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
     */
    public Builder setNestedTradeInfo(NestedTradeInfo value) {
      if (nestedTradeInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nestedTradeInfo_ = value;
      } else {
        nestedTradeInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
     */
    public Builder setNestedTradeInfo(
        NestedTradeInfo.Builder builderForValue) {
      if (nestedTradeInfoBuilder_ == null) {
        nestedTradeInfo_ = builderForValue.build();
      } else {
        nestedTradeInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
     */
    public Builder mergeNestedTradeInfo(NestedTradeInfo value) {
      if (nestedTradeInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          nestedTradeInfo_ != null &&
          nestedTradeInfo_ != NestedTradeInfo.getDefaultInstance()) {
          getNestedTradeInfoBuilder().mergeFrom(value);
        } else {
          nestedTradeInfo_ = value;
        }
      } else {
        nestedTradeInfoBuilder_.mergeFrom(value);
      }
      if (nestedTradeInfo_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
     */
    public Builder clearNestedTradeInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      nestedTradeInfo_ = null;
      if (nestedTradeInfoBuilder_ != null) {
        nestedTradeInfoBuilder_.dispose();
        nestedTradeInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
     */
    public NestedTradeInfo.Builder getNestedTradeInfoBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getNestedTradeInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
     */
    public NestedTradeInfoOrBuilder getNestedTradeInfoOrBuilder() {
      if (nestedTradeInfoBuilder_ != null) {
        return nestedTradeInfoBuilder_.getMessageOrBuilder();
      } else {
        return nestedTradeInfo_ == null ?
            NestedTradeInfo.getDefaultInstance() : nestedTradeInfo_;
      }
    }
    /**
     * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        NestedTradeInfo, NestedTradeInfo.Builder, NestedTradeInfoOrBuilder>
        getNestedTradeInfoFieldBuilder() {
      if (nestedTradeInfoBuilder_ == null) {
        nestedTradeInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            NestedTradeInfo, NestedTradeInfo.Builder, NestedTradeInfoOrBuilder>(
                getNestedTradeInfo(),
                getParentForChildren(),
                isClean());
        nestedTradeInfo_ = null;
      }
      return nestedTradeInfoBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.proto.TradeDetails)
  }

  // @@protoc_insertion_point(class_scope:com.example.proto.TradeDetails)
  private static final TradeDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TradeDetails();
  }

  public static TradeDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TradeDetails>
      PARSER = new com.google.protobuf.AbstractParser<TradeDetails>() {
    @Override
    public TradeDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TradeDetails> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TradeDetails> getParserForType() {
    return PARSER;
  }

  @Override
  public TradeDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

