// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccp_balances.proto

// Protobuf Java Version: 3.25.1
package com.example.demo.proto;

public interface TradeDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.proto.TradeDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tradeId = 1;</code>
   * @return The tradeId.
   */
  String getTradeId();
  /**
   * <code>string tradeId = 1;</code>
   * @return The bytes for tradeId.
   */
  com.google.protobuf.ByteString
      getTradeIdBytes();

  /**
   * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
   * @return Whether the nestedTradeInfo field is set.
   */
  boolean hasNestedTradeInfo();
  /**
   * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
   * @return The nestedTradeInfo.
   */
  NestedTradeInfo getNestedTradeInfo();
  /**
   * <code>.com.example.proto.NestedTradeInfo nestedTradeInfo = 2;</code>
   */
  NestedTradeInfoOrBuilder getNestedTradeInfoOrBuilder();

  /**
   * <code>string tradeKey = 3;</code>
   * @return The tradeKey.
   */
  String getTradeKey();
  /**
   * <code>string tradeKey = 3;</code>
   * @return The bytes for tradeKey.
   */
  com.google.protobuf.ByteString
      getTradeKeyBytes();
}
